[platformio]
default_envs = controller

[env]
build_unflags = -std=gnu++11
build_flags   = -std=gnu++17
upload_speed = 115200
monitor_speed = 115200

[env:controller]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<*.h> +<services/*.cpp> +<utils/*.cpp> +<module/*.cpp> +<main-${PIOENV}.cpp>
lib_deps = 
	fastled/FastLED@^3.10.3
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	adafruit/Adafruit PN532@^1.3.4

[env:speaker]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<*.h> +<services/*.cpp> +<utils/*.cpp> +<module/*.cpp> +<main-${PIOENV}.cpp>
lib_deps = 
	fastled/FastLED@^3.10.3
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	adafruit/Adafruit PN532@^1.3.4

[env:mac]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<*.h> +<main-${PIOENV}.cpp>
lib_deps = 
	adafruit/Adafruit PN532@^1.3.4

[env:test]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<*.h> +<services/*.cpp> +<utils/*.cpp> +<module/*.cpp> +<main-${PIOENV}.cpp>
lib_deps = 
	fastled/FastLED@^3.10.3
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	adafruit/Adafruit PN532@^1.3.4